version: '3'
services:
  app:
    image: 'app'
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db_data:5432/data_db
      TZ: America/New_York
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/python-docker
    networks:
      - web_global
    env_file:
      - .env

  db:
    image: "postgres:11.5-alpine"
    restart: always
    environment:
      POSTGRES_DB: data_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 5
    networks:
      - web_global

networks:
  web_global: